### ISSUE TITLE
Publishing functionality doesn't seem to declare dependencies in generated POM

### ISSUE THREAD

**Issue by bmuschko** [prokod/gradle-crossbuild-scala#103]
The integration with the `maven-publish` plugin doesn't seem to work as expected. If I expect a dependency in the project then I'd expect it to be added as transitive dependency to the generated POM file.

Consider the following example, as implemented [here](https://github.com/bmuschko/scala-multi-version/blob/main/d/build.gradle).

```
plugins {
    id 'com.github.prokod.gradle-crossbuild'
    id 'maven-publish'
}

...

dependencies {
    implementation 'org.apache.commons:commons-lang3:3.11'
}

publishing {
    publications {
        maven211(MavenPublication) {
            artifact crossBuildScala_211Jar
        }
    }
    repositories {
        maven {
            url = "$rootDir/repo"
        }
    }
}
```

Executing the publish task only generates the following `pom.xml` file without `org.apache.commons:commons-lang3:3.11` as transitive dependency.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.bmuschko</groupId>
  <artifactId>d</artifactId>
  <version>1.0.0</version>
</project>
```

Is this a bug of some sort? The [docs](https://github.com/prokod/gradle-crossbuild-scala#gradle-configurations---maven-scopes) make it sound like it should just work.

**Comment by prokod** [comment]
@bmuschko Thx for the interest :)
I am missing from your example the plugin DSL to answer that.
Please see https://github.com/prokod/gradle-crossbuild-scala#cross-building-with-publishing this section
Notice the 2nd note https://github.com/prokod/gradle-crossbuild-scala#notes-1

I hope this is sufficient for start

**Comment by bmuschko** [comment]
You can find the full build script [here](https://github.com/bmuschko/scala-multi-version/blob/main/d/build.gradle). You can see on [this line](https://github.com/bmuschko/scala-multi-version/blob/main/d/build.grad) that I am adding a script plugin. The script plugin defines the ["plugin DSL"](https://github.com/bmuschko/scala-multi-version/blob/main/gradle/scala_211.gradle#L3-L9) you are looking for I guess.

```
crossBuild {
    builds {
        scala {
            scalaVersions = ['2.11']
        }
    }
}
```

Am I missing something?

**Comment by prokod** [comment]
Hi @bmuschko see https://github.com/bmuschko/scala-multi-version/pull/1 for the changes needed. This is PR as stated in the PR description is focusing only on modules `a` and `d`

**Comment by rpalcolea** [comment]
Hi folks, wondering if it makes sense to also introduce custom components for each scala version. Something along the lines of https://docs.gradle.org/current/userguide/publishing_customization.html#sec:publishing-custom-components, for example https://github.com/johnrengelman/shadow/pull/461/files

I think having such thing could also simplify things in the future when configuring maven publications. In addition, it could add support for [Gradle Module Metadata](https://docs.gradle.org/current/userguide/publishing_gradle_module_metadata.html). Unfortunately, there is no public API for Gradle Module Metadata like `Maven.withXml`, so whatever modification you do there, it is not reflected in the GMM json file.

@melix, sorry for tagging you here but wondering if this is something that makes sense to you?

**Comment by melix** [comment]
Custom components make sense. However for Scala + GMM, I think it would make sense to standardize attributes, so that it works smoothly with Gradle. There'a s huge opportunity to simplify dependency management in the Scala ecosystem with it.

**Comment by prokod** [comment]
Hi there @rpalcolea, @melix I would argue this issue was resolved during upstream work for version 0.13. So while the current approach is working - validated this on @bmuschko repo with d_module branch, replacing the version of the plugin to 0.13 and running on root `./gradlew publishToMavenLocal`. Looking at the POM this is the updated pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.bmuschko</groupId>
  <artifactId>d_2.11</artifactId>
  <version>1.0.0</version>
  <dependencies>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>3.11</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala-library</artifactId>
      <version>2.11.12</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.bmuschko</groupId>
      <artifactId>a_2.11</artifactId>
      <version>1.0.0</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

It's a good idea to try out publishing custom components, I played that over in my mind but did not find time to go and implement it yet. Any help will be appreciated

**Comment by prokod** [comment]
Well, I take it back - so it seems the current approach is not good enough now that the plugin supports both implementation and api scopes. I will try and look on custom components for that one. Let's see where it takes me. Thx for your thoughts

**Comment by prokod** [comment]
Stale for long time already - many changes happened upstream for the general topic

**Comment by KristofConinx** [comment]
I realise this issue is closed, but can you say a few words on the status of this issue in 16.0? 
We bumped our plugin version to 16.0 after having issues with the 'api' keyword only creating runtime-scoped dependencies in the pom of the published jars (while se expect api -> compile-scoped entries in the pom).
In the latest version of the plugin (16.0), we're now seeing that we don't have any dependency entries in the pom at all anymore. 
Is the configuration proposed in the readme using `pom.withXml` the advised way to go or should the defaults that 'sort of' worked before, continue to work?

**Comment by prokod** [comment]
@KristofConinx Hi there, Thank you for trying out the plugin.

Please take a look on 0.16.0 documentation [leveraging-gradle-maven-publish-plugin](https://github.com/prokod/gradle-crossbuild-scala#leveraging-gradle-maven-publish-plugin)

Plugin 0.16.0 is now using `SoftwareComponent` to generate maven Pom. So now using `artifactId` is not enough and the plugin expects `from components.crossBuildV211`. Please note that `crossBuildV211` here is an example only and should not be used literally.

In a standard case, you do not have to use anymore `artifactId` in publication block the same as you do not need to do so also when compiling java and using `from components.java`

See also [gradle-software-components-for-scala](https://github.com/prokod/gradle-crossbuild-scala#gradle-software-components-for-scala) for more details.

I hope this will fix the issue you are having

**Comment by KristofConinx** [comment]
> @KristofConinx Hi there, Thank you for trying out the plugin.
> 
> Please take a look on 0.16.0 documentation [leveraging-gradle-maven-publish-plugin](https://github.com/prokod/gradle-crossbuild-scala#leveraging-gradle-maven-publish-plugin)
> 
> Plugin 0.16.0 is now using `SoftwareComponent` to generate maven Pom. So now using `artifactId` is not enough and the plugin expects `from components.crossBuildV211`. Please note that `crossBuildV211` here is an example only and should not be used literally.
> 
> In a standard case, you do not have to use anymore `artifactId` in publication block the same as you do not need to do so also when compiling java and using `from components.java`
> 
> See also [gradle-software-components-for-scala](https://github.com/prokod/gradle-crossbuild-scala#gradle-software-components-for-scala) for more details.
> 
> I hope this will fix the issue you are having

The `from components.java` did the trick indeed. 
Thanks!

**Comment by prokod** [comment]
@KristofConinx you should use the software component generated by the cross compile plugin not the one created by Gradle java plugin (`components.java`) otherwise you will get a pom.xml which is not controlled by the Scala cross compile plugin and the outcome is not as expected. Look please in the table in the [link](https://github.com/prokod/gradle-crossbuild-scala#builds----gradle-sourcesets-configurations-and-tasks) to figure out the sourceset name you should use for the relevant software component. The plugin creates software component for every build in the `builds` block and the naming convention of each software component is following exactly the sourceset name the plugin creates per build.(In the mentioned table that would be column `SourceSet/s`)
