### ISSUE TITLE
Publish Sources and JavaDoc

### ISSUE THREAD

**Issue by richard-gibson** [prokod/gradle-crossbuild-scala#109]
Hi is it possible to publish Sources and JavaDocs jars alongside compiled Jars?

**Comment by richard-gibson** [comment]
...if this isn't possible I'm happy to look into a PR if I can get some pointers

**Comment by prokod** [comment]
@richard-gibson Hi :)

I am not sure the plugin has this "currently under its wings" so to speak.

The plugin was written intentionally in such a way that the "standard" configuration is not touched by the plugin so you can generate javadoc and sources jar as you would otherwise.

I will be trying to simulate that in a test and hopefully come back with concrete usage example but if you have some specific feature/bug related to the interface between those tasks (javadoc, sources) and the plugin pleasedo refine this issue.

Cheers

**Comment by richard-gibson** [comment]
Hey, 
Thanks so much for taking time to look at this. Just to clarify the end goal I'm trying to achieve is something like below
```
├── multiV_2.11
│   ├── maven-metadata-local.xml
│   └── 1.0.0
│       ├── multiV_2.11-1.0.0-javadoc.jar
│       ├── multiV_2.11-1.0.0-sources.jar
│       ├── multiV_2.11-1.0.0.jar
│       └── multiV_2.11-1.0.0.pom
├── multiV_2.12
│   ├── maven-metadata-local.xml
│   └── 1.0.0
│       ├── multiV_2.12-1.0.0-javadoc.jar
│       ├── multiV_2.12-1.0.0-sources.jar
│       ├── multiV_2.12-1.0.0.jar
│       └── multiV_2.12-1.0.0.pom
└── multiV_2.13
    ├── maven-metadata-local.xml
    └── 1.0.0
        ├── multiV_2.13-1.0.0-javadoc.jar
        ├── multiV_2.13-1.0.0-sources.jar
        ├── multiV_2.13-1.0.0.jar
        └── multiV_2.13-1.0.0.pom
        
```
If its better to take the components from the standard configuration and rename that's fine. I'm just not sure how easy that is with Maven config

**Comment by richard-gibson** [comment]
As you said, all working with config below, thanks for the help
```
        java {
            withSourcesJar()
            withJavadocJar()
        }
        crossBuildScala_213(MavenPublication) {
            artifact crossBuildScala_211Jar
            artifact sourcesJar
            artifact javadocJar
        }
```
